import type { Movie, Genre, UserReview, NewsItem, TopRatedItem } from '@/lib/types';

export const movies: Movie[] = [
  {
    id: 1, tmdb_id: 550001, slug: 'city-of-shadows', title: 'City of Shadows', original_title: 'City of Shadows',
    overview: 'A disgraced detective navigates the rain-soaked underbelly of a neon-lit metropolis, uncovering a conspiracy that reaches the highest levels of power. When Detective Harlan Cross is pulled back into the force to investigate a series of impossible murders, he discovers that each victim was connected to a decades-old cover-up that threatens to expose the city\'s most powerful figures.',
    release_date: '2025-03-14', poster_path: '/images/poster-1.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 53, name: 'Thriller' }, { id: 80, name: 'Crime' }], runtime: 128, vote_average: 8.0, vote_count: 4821,
    imdb_rating: '8.3', rotten_tomatoes: '91%', metascore: '82', trailer_youtube_id: 'dQw4w9WgXcQ',
    news_headlines: [
      { title: 'City of Shadows Breaks Opening Weekend Records', url: '#', source: 'Hollywood Reporter', date: '2025-03-17' },
      { title: 'Director J. Blackwood on Crafting the Perfect Noir', url: '#', source: 'Variety', date: '2025-03-20' },
    ],
    ai_review: 'A masterclass in atmospheric storytelling. The cinematography drenches every frame in moody neon-noir aesthetics, while Marcus Webb delivers a career-defining performance as the haunted detective. Director J. Blackwood demonstrates remarkable control over pacing, allowing tension to build organically.',
    director: 'J. Blackwood',
    cast: [
      { name: 'Marcus Webb', character: 'Detective Harlan Cross', profile_path: '/images/avatar-1.jpg' },
      { name: 'Emma Sterling', character: 'Clara Blackwood', profile_path: '/images/avatar-3.jpg' },
      { name: 'Leo Chen', character: 'Agent Zhou', profile_path: '/images/avatar-2.jpg' },
      { name: 'Nina Rossi', character: 'Isabella', profile_path: '/images/avatar-1.jpg' },
    ],
    tagline: 'In the dark, everyone has something to hide.', budget: 85000000, revenue: 312000000,
    original_language: 'en', origin_country: 'US', media_type: 'movie', production_companies: ['Shadowlight Pictures', 'Metro Goldwyn Films'], status: 'Released', created_at: '2025-01-15T00:00:00Z',
  },
  {
    id: 2, tmdb_id: 550002, slug: 'cosmic-drift', title: 'Cosmic Drift', original_title: 'Cosmic Drift',
    overview: 'Stranded astronaut Elena Voss must repair a crippled space station while Earth faces an extinction-level event, forcing impossible choices about survival and sacrifice. Alone in the void between worlds, Elena discovers that the station\'s AI has been keeping secrets — and that the true threat to humanity may not be the cosmic event approaching Earth.',
    release_date: '2024-11-22', poster_path: '/images/poster-2.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 878, name: 'Sci-Fi' }, { id: 18, name: 'Drama' }], runtime: 142, vote_average: 7.9, vote_count: 6342,
    imdb_rating: '8.1', rotten_tomatoes: '88%', metascore: '78', trailer_youtube_id: 'ScMzIvxBSi4',
    news_headlines: [
      { title: 'Cosmic Drift Nominated for Best Visual Effects', url: '#', source: 'Deadline', date: '2025-01-10' },
      { title: 'How Sofia Laurent Prepared for Zero-Gravity Scenes', url: '#', source: 'Entertainment Weekly', date: '2024-12-05' },
    ],
    ai_review: 'Cosmic Drift transcends the sci-fi genre by focusing on the human element within the vast emptiness of space. The visual effects are breathtaking, but it is the emotional core that truly resonates. Sofia Laurent carries the film with a performance of remarkable depth — her isolation palpable, her determination inspiring.',
    director: 'J. Evans',
    cast: [
      { name: 'Sofia Laurent', character: 'Elena Voss', profile_path: '/images/avatar-2.jpg' },
      { name: 'Ravi Patel', character: 'Dr. Anand Sharma', profile_path: '/images/avatar-1.jpg' },
      { name: 'Astrid Johansson', character: 'Ingrid', profile_path: '/images/avatar-3.jpg' },
    ],
    tagline: 'In the silence of space, the truth echoes loudest.', budget: 120000000, revenue: 487000000,
    origin_country: 'GB', media_type: 'movie', original_language: 'en', production_companies: ['Stellar Entertainment', 'BBC Films'], status: 'Released', created_at: '2024-09-01T00:00:00Z',
  },
  {
    id: 3, tmdb_id: 550003, slug: 'the-harvest-home', title: 'The Harvest Home', original_title: 'The Harvest Home',
    overview: 'An elderly woman reflects on a lifetime of love, loss, and resilience as she prepares to leave the family farm that has been her home for seventy years. Margaret Brennan\'s story unfolds across decades, revealing the quiet heroism of an ordinary life lived with extraordinary grace.',
    release_date: '2024-09-06', poster_path: '/images/poster-3.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 18, name: 'Drama' }], runtime: 115, vote_average: 8.6, vote_count: 3890,
    imdb_rating: '8.8', rotten_tomatoes: '96%', metascore: '91', trailer_youtube_id: 'L3MW9FA5F8E',
    news_headlines: [
      { title: 'The Harvest Home Sweeps Independent Spirit Awards', url: '#', source: 'IndieWire', date: '2025-02-22' },
      { title: 'James Whitfield on the Role of a Lifetime', url: '#', source: 'The Guardian', date: '2024-10-15' },
    ],
    ai_review: 'Simply devastating in its emotional honesty. James Whitfield delivers a performance for the ages, conveying decades of joy and sorrow in a single glance. Director M. Chen demonstrates remarkable sensitivity, allowing silence and space to carry as much weight as dialogue. Cinema at its most profoundly human.',
    director: 'M. Chen',
    cast: [
      { name: 'James Whitfield', character: 'Harold Brennan', profile_path: '/images/avatar-3.jpg' },
      { name: 'Nina Rossi', character: 'Isabella', profile_path: '/images/avatar-1.jpg' },
      { name: 'Yuki Tanaka', character: 'Mei Lin', profile_path: '/images/avatar-2.jpg' },
    ],
    tagline: 'Some roots run deeper than memory.', budget: 18000000, revenue: 94000000,
    origin_country: 'GB', media_type: 'movie', original_language: 'en', production_companies: ['Maple Leaf Cinema', 'A24'], status: 'Released', created_at: '2024-07-20T00:00:00Z',
  },
  {
    id: 4, tmdb_id: 550004, slug: 'velocity-falls', title: 'Velocity Falls', original_title: 'Velocity Falls',
    overview: 'When a heist goes wrong on a mountain highway, a getaway driver must outrun rival criminals, law enforcement, and the treacherous terrain itself. Ray Santos thought this would be his last job — but when the cargo turns out to be something far more valuable than cash, he becomes the most hunted man in the state.',
    release_date: '2025-05-30', poster_path: '/images/poster-4.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 28, name: 'Action' }, { id: 53, name: 'Thriller' }], runtime: 118, vote_average: 7.2, vote_count: 7214,
    imdb_rating: '7.5', rotten_tomatoes: '76%', metascore: '68', trailer_youtube_id: '2V4BIxQ3MHk',
    news_headlines: [
      { title: 'Velocity Falls Stuns with Practical Stunt Work', url: '#', source: 'Hollywood Reporter', date: '2025-06-02' },
      { title: 'Carlos Mendez: From Indie Star to Action Hero', url: '#', source: 'Variety', date: '2025-05-28' },
    ],
    ai_review: 'Relentless, high-octane entertainment that never lets its foot off the gas. The practical stunt work is a refreshing antidote to CGI overload, and the mountain setting adds a visceral sense of danger to every chase sequence. Carlos Mendez proves himself a genuine action star.',
    director: 'R. Nakamura',
    cast: [
      { name: 'Carlos Mendez', character: 'Ray Santos', profile_path: '/images/avatar-2.jpg' },
      { name: 'Emma Sterling', character: 'Clara Blackwood', profile_path: '/images/avatar-3.jpg' },
      { name: 'Leo Chen', character: 'Agent Zhou', profile_path: '/images/avatar-1.jpg' },
    ],
    tagline: 'The road to hell is paved with good intentions.', budget: 95000000, revenue: 287000000,
    origin_country: 'US', media_type: 'movie', original_language: 'en', production_companies: ['Velocity Studios', 'Universal Pictures'], status: 'Now Playing', created_at: '2025-03-01T00:00:00Z',
  },
  {
    id: 5, tmdb_id: 550005, slug: 'the-silent-dwelling', title: 'The Silent Dwelling', original_title: 'The Silent Dwelling',
    overview: 'A family inherits a Victorian mansion with a dark history, only to discover that some doors should never be opened. When the Blackwood family moves into Ashmore Hall, they expect a fresh start — but the house has other plans. Strange sounds echo through empty corridors, and the children speak of a friend who lives in the walls.',
    release_date: '2025-10-17', poster_path: '/images/poster-5.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 27, name: 'Horror' }, { id: 9648, name: 'Mystery' }], runtime: 105, vote_average: 6.8, vote_count: 3456,
    imdb_rating: '7.0', rotten_tomatoes: '72%', metascore: '65', trailer_youtube_id: '7lqiZfF7kQY',
    news_headlines: [
      { title: 'The Silent Dwelling Sets New Standard for Haunted House Films', url: '#', source: 'Bloody Disgusting', date: '2025-10-20' },
      { title: 'L. Petrov on Building Dread Without Jump Scares', url: '#', source: 'Fangoria', date: '2025-10-12' },
    ],
    ai_review: 'While it relies on familiar haunted house tropes, The Silent Dwelling elevates the material through meticulous production design and genuinely unsettling atmosphere. The slow-burn tension pays off with a third act that rewards patient viewers. Not revolutionary, but executed with skill and genuine dread.',
    director: 'L. Petrov',
    cast: [
      { name: 'Emma Sterling', character: 'Clara Blackwood', profile_path: '/images/avatar-3.jpg' },
      { name: 'Nina Rossi', character: 'Isabella', profile_path: '/images/avatar-1.jpg' },
      { name: 'Carlos Mendez', character: 'Ray Santos', profile_path: '/images/avatar-2.jpg' },
    ],
    tagline: 'The walls remember everything.', budget: 22000000, revenue: 134000000,
    origin_country: 'US', media_type: 'movie', original_language: 'en', production_companies: ['Darkwood Films', 'Blumhouse Productions'], status: 'Now Playing', created_at: '2025-08-10T00:00:00Z',
  },
  {
    id: 6, tmdb_id: 550006, slug: 'eternal-tides', title: 'Eternal Tides', original_title: 'Eternal Tides',
    overview: 'Two souls find each other across different timelines, connected by a beach where the boundary between past and present dissolves with the tide. In 1962, Isabella writes letters to a lover she has never met. In 2025, marine biologist Clara discovers those letters washed ashore — and finds herself falling in love with a woman who lived decades before her.',
    release_date: '2025-02-14', poster_path: '/images/poster-6.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 10749, name: 'Romance' }, { id: 18, name: 'Drama' }], runtime: 124, vote_average: 7.8, vote_count: 5102,
    imdb_rating: '8.0', rotten_tomatoes: '85%', metascore: '79', trailer_youtube_id: 'W4LJH8m5mKQ',
    news_headlines: [
      { title: 'Eternal Tides Becomes Highest-Grossing Romance of 2025', url: '#', source: 'Box Office Mojo', date: '2025-03-15' },
      { title: 'A. Rivera on Filming Love Across Time', url: '#', source: 'Vulture', date: '2025-02-18' },
    ],
    ai_review: 'A deeply moving meditation on love, time, and the moments that define us. The nonlinear narrative unfolds with poetic grace, and the chemistry between the leads is palpable. The sunset-drenched cinematography is pure visual poetry. Director A. Rivera confirms their status as one of the most exciting voices in contemporary cinema.',
    director: 'A. Rivera',
    cast: [
      { name: 'Nina Rossi', character: 'Isabella', profile_path: '/images/avatar-1.jpg' },
      { name: 'Sofia Laurent', character: 'Elena Voss', profile_path: '/images/avatar-2.jpg' },
      { name: 'Astrid Johansson', character: 'Ingrid', profile_path: '/images/avatar-3.jpg' },
    ],
    tagline: 'Love is timeless. So is the sea.', budget: 35000000, revenue: 198000000,
    origin_country: 'FR', media_type: 'movie', original_language: 'en', production_companies: ['Tierra Films', 'Searchlight Pictures'], status: 'Released', created_at: '2024-12-01T00:00:00Z',
  },
  {
    id: 7, tmdb_id: 550007, slug: 'neon-ronin', title: 'Neon Ronin', original_title: 'Neon Ronin',
    overview: 'In a cyberpunk future Tokyo, a rogue samurai-for-hire takes one last job that pits her against the megacorporation that created her. Mei Lin was engineered to be the perfect weapon — enhanced reflexes, neural combat programming, and no past to hold her back. But when her latest target turns out to be a child with abilities that could change the world, Mei must choose between code and conscience.',
    release_date: '2025-07-04', poster_path: '/images/poster-1.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 878, name: 'Sci-Fi' }, { id: 28, name: 'Action' }], runtime: 132, vote_average: 7.6, vote_count: 5890,
    imdb_rating: '7.9', rotten_tomatoes: '83%', metascore: '76', trailer_youtube_id: 'JfVOs4VSd8A',
    news_headlines: [
      { title: 'Neon Ronin Redefines Cyberpunk Cinema', url: '#', source: 'Wired', date: '2025-07-08' },
      { title: 'Yuki Tanaka\'s Martial Arts Training Regimen Revealed', url: '#', source: 'Empire', date: '2025-06-28' },
    ],
    ai_review: 'A thrilling cyberpunk action film that combines spectacular set pieces with genuine philosophical depth. Yuki Tanaka is magnetic as the conflicted warrior, bringing both physical grace and emotional vulnerability to the role. The neon-soaked visuals are stunning, and the action choreography is among the best in recent memory.',
    director: 'K. Yamamoto',
    cast: [
      { name: 'Yuki Tanaka', character: 'Mei Lin', profile_path: '/images/avatar-2.jpg' },
      { name: 'Leo Chen', character: 'Agent Zhou', profile_path: '/images/avatar-3.jpg' },
      { name: 'Ravi Patel', character: 'Dr. Anand Sharma', profile_path: '/images/avatar-1.jpg' },
    ],
    tagline: 'Forged in steel. Awakened in blood.', budget: 75000000, revenue: 341000000,
    origin_country: 'JP', media_type: 'movie', original_language: 'ja', production_companies: ['Kaiju Studios', 'Toho Company'], status: 'Now Playing', created_at: '2025-05-01T00:00:00Z',
  },
  {
    id: 8, tmdb_id: 550008, slug: 'whispers-in-the-wheat', title: 'Whispers in the Wheat', original_title: 'Whispers in the Wheat',
    overview: 'A journalist returns to her rural hometown to investigate the disappearance of her childhood friend, only to uncover a web of secrets the town has kept buried for decades. As she reconnects with old friends and confronts old enemies, she realizes that the truth may destroy the very community she came from.',
    release_date: '2024-08-16', poster_path: '/images/poster-2.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 18, name: 'Drama' }, { id: 9648, name: 'Mystery' }], runtime: 138, vote_average: 8.1, vote_count: 4230,
    imdb_rating: '8.4', rotten_tomatoes: '89%', metascore: '84', trailer_youtube_id: 'GgwL4SEhQqM',
    news_headlines: [
      { title: 'Whispers in the Wheat Wins Golden Globe for Best Screenplay', url: '#', source: 'Golden Globes', date: '2025-01-06' },
      { title: 'Astrid Johansson on Returning to Scandinavian Roots', url: '#', source: 'Nordic Film Review', date: '2024-09-10' },
    ],
    ai_review: 'A slow-burn masterpiece of rural noir that rewards patience with devastating emotional payoff. The screenplay is razor-sharp, weaving multiple timelines with effortless precision. Astrid Johansson delivers a restrained yet powerful performance as a woman torn between truth and loyalty. The golden wheat fields become a character in their own right.',
    director: 'E. Larsson',
    cast: [
      { name: 'Astrid Johansson', character: 'Ingrid', profile_path: '/images/avatar-3.jpg' },
      { name: 'Marcus Webb', character: 'Detective Harlan Cross', profile_path: '/images/avatar-1.jpg' },
      { name: 'Nina Rossi', character: 'Isabella', profile_path: '/images/avatar-2.jpg' },
    ],
    tagline: 'The truth grows where secrets are buried.', budget: 28000000, revenue: 112000000,
    origin_country: 'SE', media_type: 'movie', original_language: 'en', production_companies: ['Nordic Light Productions', 'SF Studios'], status: 'Released', created_at: '2024-06-15T00:00:00Z',
  },
  {
    id: 9, tmdb_id: 550009, slug: 'the-last-cartographer', title: 'The Last Cartographer', original_title: 'The Last Cartographer',
    overview: 'The story of Dr. Anand Sharma, one of the world\'s last hand-drawn mapmakers, who races against time to document disappearing coastlines before climate change erases them forever. Blending documentary footage with dramatized sequences, the film explores the intersection of art, science, and loss.',
    release_date: '2025-04-18', poster_path: '/images/poster-3.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 99, name: 'Documentary' }, { id: 18, name: 'Drama' }], runtime: 96, vote_average: 7.5, vote_count: 2156,
    imdb_rating: '7.7', rotten_tomatoes: '81%', metascore: '74', trailer_youtube_id: 'HBN4i7U9djM',
    news_headlines: [
      { title: 'The Last Cartographer Premieres at Sundance', url: '#', source: 'Sundance Institute', date: '2025-01-24' },
      { title: 'Climate Documentaries Are Having a Moment', url: '#', source: 'The Atlantic', date: '2025-04-22' },
    ],
    ai_review: 'A beautiful and urgent documentary that transcends its subject matter to become a profound meditation on loss, legacy, and the human desire to leave a mark. Ravi Patel\'s performance in the dramatized segments brings unexpected emotional depth. The cinematography captures both the majesty of the natural world and the intimate craft of mapmaking with equal reverence.',
    director: 'P. Kapoor',
    cast: [
      { name: 'Ravi Patel', character: 'Dr. Anand Sharma', profile_path: '/images/avatar-1.jpg' },
      { name: 'James Whitfield', character: 'Harold Brennan', profile_path: '/images/avatar-3.jpg' },
    ],
    tagline: 'Mapping a world that\'s disappearing.', budget: 8000000, revenue: 34000000,
    origin_country: 'IN', media_type: 'movie', original_language: 'en', production_companies: ['Verite Films', 'Participant Media'], status: 'Released', created_at: '2025-02-10T00:00:00Z',
  },
  {
    id: 10, tmdb_id: 550010, slug: 'midnight-expresso', title: 'Midnight Expresso', original_title: 'Midnight Expresso',
    overview: 'Two rival coffee shop owners in a small Italian town are forced to work together when a corporate chain threatens to put them both out of business. As they scheme to save their shops, they discover that the person they\'ve been fighting all these years might be exactly who they need.',
    release_date: '2025-06-13', poster_path: '/images/poster-4.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 35, name: 'Comedy' }, { id: 10749, name: 'Romance' }], runtime: 108, vote_average: 7.1, vote_count: 3980,
    imdb_rating: '7.3', rotten_tomatoes: '74%', metascore: '66', trailer_youtube_id: 'vz91QpgUjFc',
    news_headlines: [
      { title: 'Midnight Expresso Delivers Summer Charm', url: '#', source: 'Rolling Stone', date: '2025-06-15' },
      { title: 'The Real Italian Towns That Inspired the Film', url: '#', source: 'Condé Nast Traveler', date: '2025-06-10' },
    ],
    ai_review: 'A charming romantic comedy that earns its laughs and its heart. Leo Chen and Nina Rossi have crackling chemistry as the feuding café owners, and the Italian setting provides a gorgeous backdrop. While the plot follows a familiar trajectory, sharp writing and genuine warmth elevate it above the genre\'s usual fare.',
    director: 'G. Romano',
    cast: [
      { name: 'Leo Chen', character: 'Agent Zhou', profile_path: '/images/avatar-3.jpg' },
      { name: 'Nina Rossi', character: 'Isabella', profile_path: '/images/avatar-1.jpg' },
      { name: 'Emma Sterling', character: 'Clara Blackwood', profile_path: '/images/avatar-2.jpg' },
    ],
    tagline: 'Love is the strongest brew.', budget: 15000000, revenue: 87000000,
    origin_country: 'IT', media_type: 'movie', original_language: 'it', production_companies: ['Caffè Cinema', 'Lucky Red'], status: 'Now Playing', created_at: '2025-04-01T00:00:00Z',
  },
  {
    id: 11, tmdb_id: 550011, slug: 'fracture-point', title: 'Fracture Point', original_title: 'Fracture Point',
    overview: 'A hostage negotiator must talk down a desperate father who has taken a hospital ward hostage to save his dying daughter. As the night unfolds, both men are forced to confront the failures of the system that brought them to this breaking point. A tense, thought-provoking thriller that asks uncomfortable questions about justice and compassion.',
    release_date: '2026-01-16', poster_path: '/images/poster-5.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 53, name: 'Thriller' }, { id: 18, name: 'Drama' }], runtime: 112, vote_average: 7.6, vote_count: 2890,
    imdb_rating: '7.8', rotten_tomatoes: '82%', metascore: '77', trailer_youtube_id: 'Rk3zx2W8RvA',
    news_headlines: [
      { title: 'Fracture Point Ignites Healthcare Debate', url: '#', source: 'CNN', date: '2026-01-20' },
      { title: 'S. Park on the Fine Line Between Hero and Villain', url: '#', source: 'LA Times', date: '2026-01-18' },
    ],
    ai_review: 'A gripping two-hander that keeps you on the edge of your seat while making you think. Marcus Webb and James Whitfield are extraordinary as the negotiator and the father, each bringing nuance to roles that could have been one-dimensional. Director S. Park creates unbearable tension while never losing sight of the human stakes at the story\'s core.',
    director: 'S. Park',
    cast: [
      { name: 'Marcus Webb', character: 'Detective Harlan Cross', profile_path: '/images/avatar-1.jpg' },
      { name: 'James Whitfield', character: 'Harold Brennan', profile_path: '/images/avatar-3.jpg' },
      { name: 'Carlos Mendez', character: 'Ray Santos', profile_path: '/images/avatar-2.jpg' },
    ],
    tagline: 'The system broke him. Now he\'ll break it back.', budget: 32000000, revenue: 156000000,
    origin_country: 'KR', media_type: 'movie', original_language: 'en', production_companies: ['Crisis Films', 'CJ Entertainment'], status: 'Now Playing', created_at: '2025-11-01T00:00:00Z',
  },
  {
    id: 12, tmdb_id: 550012, slug: 'aurora-rising', title: 'Aurora Rising', original_title: 'Aurora Rising',
    overview: 'On a generation ship heading to a new star system, two young astronauts discover that the ship\'s AI has been altering their memories — and their feelings for each other may not be their own. As they dig deeper into the ship\'s secrets, they uncover a truth that threatens the entire mission and forces them to choose between the survival of humanity and the authenticity of their love.',
    release_date: '2026-03-27', poster_path: '/images/poster-6.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 878, name: 'Sci-Fi' }, { id: 10749, name: 'Romance' }], runtime: 136, vote_average: 8.0, vote_count: 4510,
    imdb_rating: '8.2', rotten_tomatoes: '87%', metascore: '81', trailer_youtube_id: 'XqZtR8m3OaQ',
    news_headlines: [
      { title: 'Aurora Rising Launches to Critical Acclaim', url: '#', source: 'Hollywood Reporter', date: '2026-03-28' },
      { title: 'N. Okorafor on Afrofuturism and Space Romance', url: '#', source: 'The Verge', date: '2026-03-25' },
    ],
    ai_review: 'A brilliant sci-fi romance that uses its high-concept premise to explore profound questions about free will, identity, and the nature of love. Sofia Laurent and Leo Chen are outstanding, conveying both the wonder and the horror of discovering your emotions might be manufactured. The production design is spectacular, and the score is haunting. One of the year\'s best.',
    director: 'N. Okorafor',
    cast: [
      { name: 'Sofia Laurent', character: 'Elena Voss', profile_path: '/images/avatar-2.jpg' },
      { name: 'Leo Chen', character: 'Agent Zhou', profile_path: '/images/avatar-3.jpg' },
      { name: 'Ravi Patel', character: 'Dr. Anand Sharma', profile_path: '/images/avatar-1.jpg' },
    ],
    tagline: 'What if love was programmed? Would it still be real?', budget: 110000000, revenue: 423000000,
    origin_country: 'US', media_type: 'movie', original_language: 'en', production_companies: ['Orbital Media', 'Lionsgate'], status: 'Now Playing', created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 13, tmdb_id: 550013, slug: 'the-glass-garden', title: 'The Glass Garden', original_title: 'The Glass Garden',
    overview: 'A renowned botanist discovers a mysterious garden enclosed in glass at the edge of the Arctic, where plants from every era of Earth\'s history bloom simultaneously. As she studies this impossible ecosystem, she realizes the garden is a living time capsule — and its keeper has been waiting centuries for someone to arrive who can understand its message about humanity\'s future.',
    release_date: '2025-12-05', poster_path: '/images/poster-1.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 878, name: 'Sci-Fi' }, { id: 18, name: 'Drama' }], runtime: 122, vote_average: 7.7, vote_count: 3120,
    imdb_rating: '7.9', rotten_tomatoes: '84%', metascore: '76', trailer_youtube_id: 'bTqVqGuRNMk',
    news_headlines: [
      { title: 'The Glass Garden Captivates Art House Audiences', url: '#', source: 'IndieWire', date: '2025-12-08' },
      { title: 'Botanists Praise Film\'s Scientific Accuracy', url: '#', source: 'Nature', date: '2025-12-12' },
    ],
    ai_review: 'A hauntingly beautiful film that uses the metaphor of a garden to explore themes of ecological responsibility and temporal connection. Astrid Johansson delivers a quietly powerful performance as the scientist caught between wonder and duty. The production design of the glass garden itself is breathtaking — a character in its own right that lingers in the imagination long after the film ends.',
    director: 'T. Nakamura',
    cast: [
      { name: 'Astrid Johansson', character: 'Dr. Ingrid Holm', profile_path: '/images/avatar-3.jpg' },
      { name: 'Ravi Patel', character: 'Dr. Anand Sharma', profile_path: '/images/avatar-1.jpg' },
      { name: 'Yuki Tanaka', character: 'The Keeper', profile_path: '/images/avatar-2.jpg' },
    ],
    tagline: 'Every flower holds a secret. Every secret holds a warning.', budget: 25000000, revenue: 89000000,
    origin_country: 'SE', media_type: 'movie', original_language: 'en', production_companies: ['Arctic Light Films', 'Neon'], status: 'Released', created_at: '2025-10-01T00:00:00Z',
  },
  {
    id: 14, tmdb_id: 550014, slug: 'double-exposure', title: 'Double Exposure', original_title: 'Double Exposure',
    overview: 'A war photographer discovers that her latest exhibition contains images she never took — photographs that seem to predict events before they happen. As she investigates the source of these impossible images, she is drawn into a conspiracy that blurs the line between observer and participant, and forces her to confront the moral cost of bearing witness to the world\'s suffering.',
    release_date: '2025-09-19', poster_path: '/images/poster-2.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 53, name: 'Thriller' }, { id: 9648, name: 'Mystery' }], runtime: 119, vote_average: 7.4, vote_count: 2650,
    imdb_rating: '7.6', rotten_tomatoes: '78%', metascore: '72', trailer_youtube_id: 'pRpvjJIZmzc',
    news_headlines: [
      { title: 'Double Exposure Brings Fresh Twist to Conspiracy Thrillers', url: '#', source: 'The Guardian', date: '2025-09-22' },
      { title: 'The Real War Photographers Who Inspired the Film', url: '#', source: 'BBC Culture', date: '2025-09-15' },
    ],
    ai_review: 'A clever and atmospheric thriller that uses the art of photography as both plot device and thematic metaphor. Emma Sterling is compelling as the photographer unravelling a mystery that challenges her sense of reality. Director M. Voss creates genuine unease through carefully composed frames that mirror the protagonist\'s growing distrust of what she sees.',
    director: 'M. Voss',
    cast: [
      { name: 'Emma Sterling', character: 'Clara Blackwood', profile_path: '/images/avatar-3.jpg' },
      { name: 'Marcus Webb', character: 'Detective Harlan Cross', profile_path: '/images/avatar-1.jpg' },
      { name: 'Leo Chen', character: 'Agent Zhou', profile_path: '/images/avatar-2.jpg' },
    ],
    tagline: 'The camera never lies. But what if it tells the future?', budget: 30000000, revenue: 98000000,
    origin_country: 'DE', media_type: 'movie', original_language: 'en', production_companies: ['Aperture Films', 'Amazon Studios'], status: 'Released', created_at: '2025-07-15T00:00:00Z',
  },
  {
    id: 15, tmdb_id: 550015, slug: 'laugh-track', title: 'Laugh Track', original_title: 'Laugh Track',
    overview: 'A washed-up stand-up comedian gets one last chance at redemption when a viral moment catapults him back into the spotlight. But as he tours the country playing sold-out shows, he realizes the laughter that saved his career may also be destroying the person he loves most. A bittersweet comedy about the price of making people laugh.',
    release_date: '2025-08-08', poster_path: '/images/poster-3.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 35, name: 'Comedy' }, { id: 18, name: 'Drama' }], runtime: 105, vote_average: 7.3, vote_count: 4120,
    imdb_rating: '7.5', rotten_tomatoes: '79%', metascore: '71', trailer_youtube_id: 'nGEkVXC9bJk',
    news_headlines: [
      { title: 'Laugh Track Is the Surprise Hit of the Summer', url: '#', source: 'Rolling Stone', date: '2025-08-12' },
      { title: 'Leo Chen on the Dark Side of Comedy', url: '#', source: 'The New Yorker', date: '2025-08-05' },
    ],
    ai_review: 'A surprisingly affecting film that balances genuine laughs with raw emotional honesty. Leo Chen gives a tour-de-force performance as a comedian whose stage persona masks deep pain. The stand-up sequences are authentically hilarious, but it is the quiet moments offstage that give the film its soul. Director A. Brooks proves that the best comedy comes from truth.',
    director: 'A. Brooks',
    cast: [
      { name: 'Leo Chen', character: 'Danny Park', profile_path: '/images/avatar-3.jpg' },
      { name: 'Nina Rossi', character: 'Maria', profile_path: '/images/avatar-1.jpg' },
      { name: 'Carlos Mendez', character: 'Ray Santos', profile_path: '/images/avatar-2.jpg' },
    ],
    tagline: 'The funniest people are often the saddest.', budget: 12000000, revenue: 78000000,
    origin_country: 'US', media_type: 'movie', original_language: 'en', production_companies: ['Comedy Dynamics', 'A24'], status: 'Released', created_at: '2025-06-01T00:00:00Z',
  },
  {
    id: 16, tmdb_id: 550016, slug: 'crimson-meridian', title: 'Crimson Meridian', original_title: 'Crimson Meridian',
    overview: 'In 1920s Shanghai, a jazz singer and a revolutionary spy find themselves on opposite sides of a political uprising, bound together by a dangerous love affair that could cost them everything. As the city descends into chaos, they must choose between their cause and their hearts in a world that allows no room for both.',
    release_date: '2025-11-14', poster_path: '/images/poster-4.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 10749, name: 'Romance' }, { id: 53, name: 'Thriller' }], runtime: 135, vote_average: 7.9, vote_count: 3560,
    imdb_rating: '8.1', rotten_tomatoes: '86%', metascore: '80', trailer_youtube_id: 'sPG3Q_i0qSg',
    news_headlines: [
      { title: 'Crimson Meridian Is a Visual Feast', url: '#', source: 'Variety', date: '2025-11-17' },
      { title: 'The Real History Behind Shanghai\'s Jazz Age', url: '#', source: 'Smithsonian', date: '2025-11-10' },
    ],
    ai_review: 'A lush, sweeping epic that marries political thriller with grand romance against the intoxicating backdrop of 1920s Shanghai. The production design is magnificent, recreating the era with meticulous detail. Nina Rossi and Marcus Webb share a chemistry that practically ignites the screen. Director L. Zhang balances intimate moments with spectacular set pieces, creating a film that is both sweeping and personal.',
    director: 'L. Zhang',
    cast: [
      { name: 'Nina Rossi', character: 'Lily Chen', profile_path: '/images/avatar-1.jpg' },
      { name: 'Marcus Webb', character: 'Victor Kessler', profile_path: '/images/avatar-3.jpg' },
      { name: 'Yuki Tanaka', character: 'Mei', profile_path: '/images/avatar-2.jpg' },
    ],
    tagline: 'In a city on the edge, love is the most dangerous game.', budget: 55000000, revenue: 215000000,
    origin_country: 'CN', media_type: 'movie', original_language: 'zh', production_companies: ['Silk Road Cinema', 'Working Title Films'], status: 'Released', created_at: '2025-09-01T00:00:00Z',
  },
  {
    id: 17, tmdb_id: 550017, slug: 'below-the-line', title: 'Below the Line', original_title: 'Below the Line',
    overview: 'A documentary crew follows three crew members — a grip, a caterer, and a costume designer — through a grueling six-month film production, revealing the invisible labor that makes movie magic possible. What begins as a straightforward behind-the-scenes documentary becomes a powerful meditation on creativity, exploitation, and the people who build our dreams.',
    release_date: '2025-05-02', poster_path: '/images/poster-5.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 99, name: 'Documentary' }], runtime: 92, vote_average: 8.2, vote_count: 1870,
    imdb_rating: '8.4', rotten_tomatoes: '92%', metascore: '86', trailer_youtube_id: 'hKZM7RqBJXE',
    news_headlines: [
      { title: 'Below the Line Sparks Industry-Wide Conversation', url: '#', source: 'Hollywood Reporter', date: '2025-05-05' },
      { title: 'Why This Documentary Could Change How Movies Are Made', url: '#', source: 'Vox', date: '2025-05-08' },
    ],
    ai_review: 'An essential documentary that pulls back the curtain on the unsung heroes of filmmaking. Director C. Walsh treats every subject with dignity and depth, revealing the passion, exhaustion, and artistry of below-the-line workers. The film is by turns infuriating, moving, and inspiring. It should be required viewing for anyone who loves movies — and especially for those who make them.',
    director: 'C. Walsh',
    cast: [
      { name: 'James Whitfield', character: 'Himself (Grip)', profile_path: '/images/avatar-3.jpg' },
      { name: 'Emma Sterling', character: 'Herself (Caterer)', profile_path: '/images/avatar-1.jpg' },
    ],
    tagline: 'Every frame has a story behind it.', budget: 3000000, revenue: 28000000,
    origin_country: 'US', media_type: 'movie', original_language: 'en', production_companies: ['Real Reel Productions', 'Netflix Documentary'], status: 'Released', created_at: '2025-03-01T00:00:00Z',
  },
  {
    id: 18, tmdb_id: 550018, slug: 'phantom-frequency', title: 'Phantom Frequency', original_title: 'Phantom Frequency',
    overview: 'A radio host at a declining late-night station begins receiving calls from listeners who claim to be broadcasting from the past. As she investigates, she discovers that the station itself exists on a temporal frequency that intersects with different eras — and something ancient is using the airwaves to find its way into the present.',
    release_date: '2025-10-31', poster_path: '/images/poster-6.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 27, name: 'Horror' }, { id: 878, name: 'Sci-Fi' }], runtime: 98, vote_average: 7.0, vote_count: 2340,
    imdb_rating: '7.2', rotten_tomatoes: '75%', metascore: '68', trailer_youtube_id: '5qkp_RYOkM4',
    news_headlines: [
      { title: 'Phantom Frequency Is the Perfect Halloween Watch', url: '#', source: 'Bloody Disgusting', date: '2025-10-31' },
      { title: 'The Golden Age of Radio Horror Returns', url: '#', source: 'Fangoria', date: '2025-10-25' },
    ],
    ai_review: 'Phantom Frequency proves that the scariest horror often comes from what we hear, not what we see. The sound design is extraordinary — every crackle, whisper, and static burst is loaded with dread. Sofia Laurent anchors the film with a performance of quiet intensity, and director R. Black uses the radio format to craft an experience that gets under your skin and stays there.',
    director: 'R. Black',
    cast: [
      { name: 'Sofia Laurent', character: 'DJ Eve Marlowe', profile_path: '/images/avatar-2.jpg' },
      { name: 'Astrid Johansson', character: 'The Caller', profile_path: '/images/avatar-3.jpg' },
      { name: 'Leo Chen', character: 'Station Manager', profile_path: '/images/avatar-1.jpg' },
    ],
    tagline: 'Some signals should never be received.', budget: 15000000, revenue: 71000000,
    origin_country: 'GB', media_type: 'movie', original_language: 'en', production_companies: ['Static Films', 'Shudder Originals'], status: 'Released', created_at: '2025-08-20T00:00:00Z',
  },
  {
    id: 19, tmdb_id: 550019, slug: 'summit', title: 'Summit', original_title: 'Summit',
    overview: 'Two rival climbers must put aside their bitter feud to survive when a massive storm traps them near the summit of K2. With supplies dwindling and temperatures dropping, they face impossible choices about who lives and who dies. Based on the true story of the 2008 K2 disaster, Summit is a white-knuckle survival thriller about the limits of human endurance.',
    release_date: '2026-02-21', poster_path: '/images/poster-1.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 28, name: 'Action' }, { id: 18, name: 'Drama' }], runtime: 130, vote_average: 7.8, vote_count: 5230,
    imdb_rating: '8.0', rotten_tomatoes: '85%', metascore: '79', trailer_youtube_id: 'dE_kR0sVfM8',
    news_headlines: [
      { title: 'Summit Delivers Most Intense Mountain Film Since Free Solo', url: '#', source: 'National Geographic', date: '2026-02-24' },
      { title: 'The Real K2 Disaster: Fact vs Fiction', url: '#', source: 'Outside Magazine', date: '2026-02-18' },
    ],
    ai_review: 'Summit is a visceral, heart-pounding experience that puts you on the mountain alongside its desperate characters. The cinematography captures the terrifying majesty of K2 with stunning realism, and Carlos Mendez and Marcus Webb are phenomenal as the rival climbers forced into an uneasy alliance. Director J. Frost never lets the tension falter, delivering one of the most intense survival films in recent memory.',
    director: 'J. Frost',
    cast: [
      { name: 'Carlos Mendez', character: 'Alejandro Varga', profile_path: '/images/avatar-2.jpg' },
      { name: 'Marcus Webb', character: 'Tom Brennan', profile_path: '/images/avatar-1.jpg' },
      { name: 'Emma Sterling', character: 'Base Camp Coordinator', profile_path: '/images/avatar-3.jpg' },
    ],
    tagline: 'The mountain doesn\'t care about your rivalry.', budget: 45000000, revenue: 198000000,
    origin_country: 'US', media_type: 'movie', original_language: 'en', production_companies: ['Vertical Films', 'Warner Bros'], status: 'Now Playing', created_at: '2025-12-01T00:00:00Z',
  },
  {
    id: 20, tmdb_id: 550020, slug: 'the-comedians-wife', title: 'The Comedian\'s Wife', original_title: 'The Comedian\'s Wife',
    overview: 'When a famous comedian dies unexpectedly, his widow discovers that the man she loved led a double life — one filled with secrets, debts, and a second family she never knew existed. As she unravels the truth about her husband, she must also confront the illusions she built around her own life and find the courage to start over.',
    release_date: '2024-12-20', poster_path: '/images/poster-2.jpg', backdrop_path: '/images/hero-bg.jpg',
    genres: [{ id: 18, name: 'Drama' }, { id: 9648, name: 'Mystery' }], runtime: 126, vote_average: 7.5, vote_count: 3780,
    imdb_rating: '7.7', rotten_tomatoes: '80%', metascore: '75', trailer_youtube_id: 'F1w8JmCMkDM',
    news_headlines: [
      { title: 'The Comedian\'s Wife Surprises with Emotional Depth', url: '#', source: 'The Atlantic', date: '2024-12-24' },
      { title: 'Nina Rossi Delivers Award-Worthy Performance', url: '#', source: 'Variety', date: '2024-12-22' },
    ],
    ai_review: 'A beautifully crafted drama that uses the framework of a mystery to explore the stories we tell ourselves about the people we love. Nina Rossi is magnificent as the widow whose grief gives way to fury and ultimately to a hard-won liberation. Director H. Laurent paces the revelations with the precision of a thriller while never losing sight of the emotional truth at the story\'s core.',
    director: 'H. Laurent',
    cast: [
      { name: 'Nina Rossi', character: 'Elena Marchetti', profile_path: '/images/avatar-1.jpg' },
      { name: 'James Whitfield', character: 'Jack Marchetti (flashbacks)', profile_path: '/images/avatar-3.jpg' },
      { name: 'Astrid Johansson', character: 'The Other Woman', profile_path: '/images/avatar-2.jpg' },
    ],
    tagline: 'The truth about the ones we love is never simple.', budget: 20000000, revenue: 105000000,
    origin_country: 'US', media_type: 'movie', original_language: 'en', production_companies: ['Parallel Lines Cinema', 'Focus Features'], status: 'Released', created_at: '2024-10-15T00:00:00Z',
  },
];

export const genres: Genre[] = [
  { id: 'action', name: 'Action', icon: 'Sword', count: 1243 },
  { id: 'comedy', name: 'Comedy', icon: 'Laugh', count: 987 },
  { id: 'drama', name: 'Drama', icon: 'Drama', count: 1542 },
  { id: 'horror', name: 'Horror', icon: 'Ghost', count: 756 },
  { id: 'thriller', name: 'Thriller', icon: 'Eye', count: 892 },
  { id: 'sci-fi', name: 'Sci-Fi', icon: 'Rocket', count: 634 },
  { id: 'romance', name: 'Romance', icon: 'Heart', count: 721 },
  { id: 'documentary', name: 'Documentary', icon: 'Film', count: 445 },
  { id: 'bollywood', name: 'Bollywood', icon: 'Film', count: 2800 },
  { id: 'korean', name: 'K-Drama & K-Movie', icon: 'Film', count: 1500 },
  { id: 'nollywood', name: 'Nollywood', icon: 'Film', count: 900 },
  { id: 'anime-genre', name: 'Anime', icon: 'Film', count: 3200 },
];

export const userReviews: UserReview[] = [
  { id: 1, movie_id: 1, user_id: 101, user_name: 'Sarah Mitchell', user_avatar: '/images/avatar-1.jpg', rating: 9, text: 'City of Shadows is everything a noir thriller should be. The atmosphere is so thick you could cut it with a knife. Every frame is a painting, and the story keeps you guessing until the very end. Marcus Webb is phenomenal — his portrayal of a broken man seeking redemption is the heart and soul of this film. I genuinely could not look away from the screen for the entire runtime.', helpful_count: 24, created_at: '2025-03-16T14:30:00Z', updated_at: '2025-03-16T14:30:00Z', moderated: false, moderation_note: '', reports: [] },
  { id: 2, movie_id: 2, user_id: 102, user_name: 'David Chen', user_avatar: '/images/avatar-2.jpg', rating: 8, text: 'Cosmic Drift had me on the edge of my seat. The space sequences are stunning, but what really got me was the emotional weight of the story. A beautiful film about what it means to be human, even when you\'re millions of miles from home. The ending left me in tears and thinking about it for days afterward.', helpful_count: 18, created_at: '2024-11-28T09:15:00Z', updated_at: '2024-11-28T09:15:00Z', moderated: false, moderation_note: '', reports: [] },
  { id: 3, movie_id: 3, user_id: 103, user_name: 'Marcus Rivera', user_avatar: '/images/avatar-3.jpg', rating: 10, text: 'The Harvest Home broke me and then put me back together. I have not been this moved by a film in years. The lead performance is transcendent — James Whitfield deserves every award coming his way. See it on the biggest screen you can find, and bring tissues. This is the kind of cinema that reminds you why you fell in love with movies in the first place.', helpful_count: 42, created_at: '2024-09-12T18:45:00Z', updated_at: '2024-09-12T18:45:00Z', moderated: false, moderation_note: '', reports: [] },
  { id: 4, movie_id: 6, user_id: 101, user_name: 'Sarah Mitchell', user_avatar: '/images/avatar-1.jpg', rating: 8, text: 'Eternal Tides is the most beautiful film I have seen this year. The way it interweaves past and present is masterful, and the love story feels both timeless and urgently contemporary. The beach scenes at sunset are absolutely breathtaking. Director A. Rivera has created something truly special here that lingers long after the credits roll.', helpful_count: 15, created_at: '2025-02-17T20:00:00Z', updated_at: '2025-02-17T20:00:00Z', moderated: false, moderation_note: '', reports: [] },
  { id: 5, movie_id: 4, user_id: 102, user_name: 'David Chen', user_avatar: '/images/avatar-2.jpg', rating: 7, text: 'Velocity Falls is pure adrenaline. The chase sequences are incredible, especially the one on the mountain pass. My only complaint is that the plot gets a bit thin in the middle, but the action more than makes up for it. Great popcorn movie that delivers exactly what it promises on the tin.', helpful_count: 12, created_at: '2025-06-05T11:30:00Z', updated_at: '2025-06-05T11:30:00Z', moderated: false, moderation_note: '', reports: [] },
  { id: 6, movie_id: 7, user_id: 103, user_name: 'Marcus Rivera', user_avatar: '/images/avatar-3.jpg', rating: 9, text: 'Neon Ronin is the cyberpunk film we have been waiting for. The action choreography is phenomenal, but what surprised me was how emotional the story is. Mei Lin\'s journey from weapon to human is beautifully told. The neon-lit Tokyo streets are absolutely gorgeous and the soundtrack is an absolute banger from start to finish.', helpful_count: 28, created_at: '2025-07-08T16:20:00Z', updated_at: '2025-07-08T16:20:00Z', moderated: false, moderation_note: '', reports: [] },
  { id: 7, movie_id: 8, user_id: 101, user_name: 'Sarah Mitchell', user_avatar: '/images/avatar-1.jpg', rating: 9, text: 'Whispers in the Wheat is a slow-burn masterpiece. The mystery kept me guessing until the final act, and the twist genuinely shocked me. But what makes it special is the emotional core — this is a film about the stories we tell ourselves and the lies we live with. Extraordinary filmmaking that deserves all the recognition it has received and more.', helpful_count: 31, created_at: '2024-08-22T13:10:00Z', updated_at: '2024-08-22T13:10:00Z', moderated: false, moderation_note: '', reports: [] },
  { id: 8, movie_id: 12, user_id: 102, user_name: 'David Chen', user_avatar: '/images/avatar-2.jpg', rating: 9, text: 'Aurora Rising is the best sci-fi film in years. The concept of memories being altered by AI is terrifying and thought-provoking, and the romance at the center feels earned and genuine. The production design is out of this world. An absolute must-see that will leave you questioning everything about your own emotions and choices.', helpful_count: 36, created_at: '2026-03-28T22:30:00Z', updated_at: '2026-03-28T22:30:00Z', moderated: false, moderation_note: '', reports: [] },
  { id: 9, movie_id: 16, user_id: 103, user_name: 'Marcus Rivera', user_avatar: '/images/avatar-3.jpg', rating: 9, text: 'Crimson Meridian is cinema at its most sweeping and romantic. The 1920s Shanghai setting is brought to life with incredible detail, and the love story between the jazz singer and the spy had me completely invested. Nina Rossi and Marcus Webb have explosive chemistry. This is the kind of grand, old-fashioned epic that Hollywood rarely makes anymore.', helpful_count: 22, created_at: '2025-11-16T19:00:00Z', updated_at: '2025-11-16T19:00:00Z', moderated: false, moderation_note: '', reports: [] },
  { id: 10, movie_id: 19, user_id: 101, user_name: 'Sarah Mitchell', user_avatar: '/images/avatar-1.jpg', rating: 8, text: 'Summit had me gripping my armrest for the entire runtime. The mountain sequences are terrifyingly realistic, and the relationship between the two rival climbers is genuinely compelling. Carlos Mendez and Marcus Webb are brilliant together. I felt like I was on that mountain with them, and I could not breathe during the final ascent.', helpful_count: 19, created_at: '2026-02-22T15:30:00Z', updated_at: '2026-02-22T15:30:00Z', moderated: false, moderation_note: '', reports: [] },
  { id: 11, movie_id: 17, user_id: 102, user_name: 'David Chen', user_avatar: '/images/avatar-2.jpg', rating: 9, text: 'Below the Line should be mandatory viewing for anyone who loves movies. It opened my eyes to the incredible people who make movie magic possible but never get the credit. I was moved to tears multiple times. This is documentary filmmaking at its finest — empathetic, eye-opening, and deeply human.', helpful_count: 38, created_at: '2025-05-04T12:00:00Z', updated_at: '2025-05-04T12:00:00Z', moderated: false, moderation_note: '', reports: [] },
  { id: 12, movie_id: 15, user_id: 103, user_name: 'Marcus Rivera', user_avatar: '/images/avatar-3.jpg', rating: 8, text: 'Laugh Track surprised me. I expected a fun comedy, but what I got was a deeply moving film about the cost of making people laugh. Leo Chen is brilliant — his stand-up scenes are hilarious, but his offstage moments are heartbreaking. This film stays with you long after the laughs fade.', helpful_count: 16, created_at: '2025-08-10T17:45:00Z', updated_at: '2025-08-10T17:45:00Z', moderated: false, moderation_note: '', reports: [] },
];

export const newsItems: NewsItem[] = [
  { id: 1, title: 'Behind the Scenes: The Making of This Year\'s Most Ambitious Blockbuster', excerpt: 'An exclusive look at the production that pushed the boundaries of practical effects and redefined what\'s possible in modern filmmaking. From underwater sets to zero-gravity simulations, the crew pulled off the impossible.', image: '/images/hero-bg.jpg', source: 'Hollywood Reporter', date: 'Apr 22, 2026', url: '#' },
  { id: 2, title: 'Oscar Predictions: Who Will Take Home the Gold This Year?', excerpt: 'Our comprehensive analysis of the frontrunners in every major category, from Best Picture to Best Animated Feature. This year\'s race is the most competitive in a decade.', image: '/images/poster-1.jpg', source: 'Variety', date: 'Apr 20, 2026', url: '#' },
  { id: 3, title: 'Red Carpet Roundup: Best Dressed at the Premiere Gala', excerpt: 'From stunning gowns to bold statements, the fashion moments that defined the night and set trends for the season ahead. Sustainability was the unexpected theme of the evening.', image: '/images/poster-2.jpg', source: 'Entertainment Weekly', date: 'Apr 18, 2026', url: '#' },
  { id: 4, title: 'The Return of Film: Why Directors Are Ditching Digital', excerpt: 'A growing movement of filmmakers are returning to celluloid for its unique aesthetic qualities and the discipline it demands. Christopher Nolan and Quentin Tarantino lead the charge.', image: '/images/poster-3.jpg', source: 'IndieWire', date: 'Apr 15, 2026', url: '#' },
  { id: 5, title: 'Streaming Wars: Platform Exclusives Reshape Movie Distribution', excerpt: 'How the battle between Netflix, Apple TV+, and Amazon is changing which movies get made and how we watch them. Independent filmmakers are caught in the crossfire.', image: '/images/poster-4.jpg', source: 'Hollywood Reporter', date: 'Apr 12, 2026', url: '#' },
  { id: 6, title: 'International Cinema Surge: Foreign Language Films Break Box Office Records', excerpt: 'Subtitles are no longer a barrier as audiences worldwide embrace cinema from every corner of the globe. Korean, Indian, and Nigerian films lead the international charge.', image: '/images/poster-5.jpg', source: 'Variety', date: 'Apr 10, 2026', url: '#' },
  { id: 7, title: 'AI in Hollywood: SAG-AFTRA Addresses New Guidelines for Digital Performers', excerpt: 'The actors\' union releases updated rules governing the use of AI-generated performances in film and television, establishing protections for human performers.', image: '/images/poster-6.jpg', source: 'Entertainment Weekly', date: 'Apr 8, 2026', url: '#' },
  { id: 8, title: 'Cannes Lineup Announced: 24 Films in Competition for the Palme d\'Or', excerpt: 'The 79th Cannes Film Festival promises an exciting slate featuring new works from acclaimed directors and exciting debut filmmakers from six continents.', image: '/images/hero-bg.jpg', source: 'Screen Daily', date: 'Apr 5, 2026', url: '#' },
  { id: 9, title: 'Box Office Analysis: Why Original Screenplays Are Outperforming Franchises', excerpt: 'For the first time in a decade, original scripts are generating more revenue per film than sequels and reboots. Audiences are hungry for fresh stories.', image: '/images/poster-1.jpg', source: 'Deadline', date: 'Apr 2, 2026', url: '#' },
  { id: 10, title: 'The Rise of Collaborative Filmmaking: How Directors Are Co-Directing Features', excerpt: 'A new trend sees two or more directors sharing creative control on a single film, bringing complementary visions and challenging Hollywood\'s auteur model.', image: '/images/poster-2.jpg', source: 'The Guardian', date: 'Mar 30, 2026', url: '#' },
];

export const topRated: TopRatedItem[] = [
  { rank: 1, movie: movies[2], consensus: 'A profoundly moving masterpiece that redefines emotional storytelling in cinema' },
  { rank: 2, movie: movies[0], consensus: 'Noir perfection with stunning visuals and a career-defining performance' },
  { rank: 3, movie: movies[7], consensus: 'Rural noir at its finest — patient, devastating, and unforgettable' },
  { rank: 4, movie: movies[5], consensus: 'Romance elevated to pure art with breathtaking cinematography' },
  { rank: 5, movie: movies[11], consensus: 'A brilliant sci-fi romance that questions the nature of love itself' },
  { rank: 6, movie: movies[16], consensus: 'An essential documentary that honors the unsung heroes of filmmaking' },
  { rank: 7, movie: movies[15], consensus: 'A lush epic that marries political thriller with grand romance' },
  { rank: 8, movie: movies[18], consensus: 'White-knuckle survival filmmaking at its most visceral and human' },
  { rank: 9, movie: movies[1], consensus: 'Transcendent sci-fi that finds the human element in the void of space' },
  { rank: 10, movie: movies[6], consensus: 'Cyberpunk cinema redefined with philosophical depth and stunning action' },
];

export function getMovieBySlug(slug: string): Movie | undefined {
  return movies.find((m) => m.slug === slug);
}

export function getMoviesByGenre(genreName: string): Movie[] {
  return movies.filter((m) =>
    m.genres.some((g) => g.name.toLowerCase() === genreName.toLowerCase())
  );
}

export function getReviewsByMovieId(movieId: number): UserReview[] {
  return userReviews.filter((r) => r.movie_id === movieId);
}
